global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'assurance-service'
    static_configs:
      - targets: ['assurance-service:8000']

  - job_name: 'mms_api'
    static_configs:
      - targets: ['mms_api:9100']
